const { Schema, model } = require('mongoose');

// An _id will be auto generated by mongoose
const TopicSchema = new Schema({
  title: {type: String, required: true},
  // dont call Date.now() here
  published_at: {type: Date, default: Date.now},
  score: {type: Number, default: 0}
})

const Topic = model('Topic', TopicSchema);

module.exports = Topic

